// Code generated by MockGen. DO NOT EDIT.
// Source: internal\domain\repositories\webhook_queue_repository.go
//
// Generated by this command:
//
//	mockgen -source internal\domain\repositories\webhook_queue_repository.go -destination internal\mocks\mock_webhook_queue_repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"
	entities "webhook-processor/internal/domain/entities"

	gomock "go.uber.org/mock/gomock"
)

// MockWebhookQueueRepository is a mock of WebhookQueueRepository interface.
type MockWebhookQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookQueueRepositoryMockRecorder
	isgomock struct{}
}

// MockWebhookQueueRepositoryMockRecorder is the mock recorder for MockWebhookQueueRepository.
type MockWebhookQueueRepositoryMockRecorder struct {
	mock *MockWebhookQueueRepository
}

// NewMockWebhookQueueRepository creates a new mock instance.
func NewMockWebhookQueueRepository(ctrl *gomock.Controller) *MockWebhookQueueRepository {
	mock := &MockWebhookQueueRepository{ctrl: ctrl}
	mock.recorder = &MockWebhookQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookQueueRepository) EXPECT() *MockWebhookQueueRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWebhookQueueRepository) Create(ctx context.Context, webhook *entities.WebhookQueue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, webhook)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWebhookQueueRepositoryMockRecorder) Create(ctx, webhook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebhookQueueRepository)(nil).Create), ctx, webhook)
}

// GetNextWebhookForProcessing mocks base method.
func (m *MockWebhookQueueRepository) GetNextWebhookForProcessing(ctx context.Context, workerID string, retryLevel int) (*entities.WebhookQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextWebhookForProcessing", ctx, workerID, retryLevel)
	ret0, _ := ret[0].(*entities.WebhookQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextWebhookForProcessing indicates an expected call of GetNextWebhookForProcessing.
func (mr *MockWebhookQueueRepositoryMockRecorder) GetNextWebhookForProcessing(ctx, workerID, retryLevel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextWebhookForProcessing", reflect.TypeOf((*MockWebhookQueueRepository)(nil).GetNextWebhookForProcessing), ctx, workerID, retryLevel)
}

// MarkCompleted mocks base method.
func (m *MockWebhookQueueRepository) MarkCompleted(ctx context.Context, webhookID int64, processingStartedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCompleted", ctx, webhookID, processingStartedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCompleted indicates an expected call of MarkCompleted.
func (mr *MockWebhookQueueRepositoryMockRecorder) MarkCompleted(ctx, webhookID, processingStartedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompleted", reflect.TypeOf((*MockWebhookQueueRepository)(nil).MarkCompleted), ctx, webhookID, processingStartedAt)
}

// MarkFailed mocks base method.
func (m *MockWebhookQueueRepository) MarkFailed(ctx context.Context, webhookID int64, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, webhookID, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockWebhookQueueRepositoryMockRecorder) MarkFailed(ctx, webhookID, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockWebhookQueueRepository)(nil).MarkFailed), ctx, webhookID, errorMsg)
}

// Update mocks base method.
func (m *MockWebhookQueueRepository) Update(ctx context.Context, webhook *entities.WebhookQueue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, webhook)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWebhookQueueRepositoryMockRecorder) Update(ctx, webhook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWebhookQueueRepository)(nil).Update), ctx, webhook)
}

// UpdateRetryAttempt mocks base method.
func (m *MockWebhookQueueRepository) UpdateRetryAttempt(ctx context.Context, webhookID int64, retryLevel int, startedAt time.Time, completedAt *time.Time, durationMs int64, httpStatus int, responseBody, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRetryAttempt", ctx, webhookID, retryLevel, startedAt, completedAt, durationMs, httpStatus, responseBody, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRetryAttempt indicates an expected call of UpdateRetryAttempt.
func (mr *MockWebhookQueueRepositoryMockRecorder) UpdateRetryAttempt(ctx, webhookID, retryLevel, startedAt, completedAt, durationMs, httpStatus, responseBody, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRetryAttempt", reflect.TypeOf((*MockWebhookQueueRepository)(nil).UpdateRetryAttempt), ctx, webhookID, retryLevel, startedAt, completedAt, durationMs, httpStatus, responseBody, errorMsg)
}
