// Code generated by MockGen. DO NOT EDIT.
// Source: internal\domain\services\webhook_service.go
//
// Generated by this command:
//
//	mockgen -source internal\domain\services\webhook_service.go -destination internal\mocks\mock_webhook_service.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entities "webhook-processor/internal/domain/entities"
	services "webhook-processor/internal/domain/services"

	gomock "go.uber.org/mock/gomock"
)

// MockWebhookService is a mock of WebhookService interface.
type MockWebhookService struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookServiceMockRecorder
	isgomock struct{}
}

// MockWebhookServiceMockRecorder is the mock recorder for MockWebhookService.
type MockWebhookServiceMockRecorder struct {
	mock *MockWebhookService
}

// NewMockWebhookService creates a new mock instance.
func NewMockWebhookService(ctrl *gomock.Controller) *MockWebhookService {
	mock := &MockWebhookService{ctrl: ctrl}
	mock.recorder = &MockWebhookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookService) EXPECT() *MockWebhookServiceMockRecorder {
	return m.recorder
}

// SendWebhook mocks base method.
func (m *MockWebhookService) SendWebhook(ctx context.Context, webhook *entities.WebhookQueue) (*services.WebhookResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWebhook", ctx, webhook)
	ret0, _ := ret[0].(*services.WebhookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendWebhook indicates an expected call of SendWebhook.
func (mr *MockWebhookServiceMockRecorder) SendWebhook(ctx, webhook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWebhook", reflect.TypeOf((*MockWebhookService)(nil).SendWebhook), ctx, webhook)
}
