// Code generated by MockGen. DO NOT EDIT.
// Source: internal\domain\repositories\webhook_config_repository.go
//
// Generated by this command:
//
//	mockgen -source internal\domain\repositories\webhook_config_repository.go -destination internal\mocks\mock_webhook_config_repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entities "webhook-processor/internal/domain/entities"

	gomock "go.uber.org/mock/gomock"
)

// MockWebhookConfigRepository is a mock of WebhookConfigRepository interface.
type MockWebhookConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockWebhookConfigRepositoryMockRecorder is the mock recorder for MockWebhookConfigRepository.
type MockWebhookConfigRepositoryMockRecorder struct {
	mock *MockWebhookConfigRepository
}

// NewMockWebhookConfigRepository creates a new mock instance.
func NewMockWebhookConfigRepository(ctrl *gomock.Controller) *MockWebhookConfigRepository {
	mock := &MockWebhookConfigRepository{ctrl: ctrl}
	mock.recorder = &MockWebhookConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookConfigRepository) EXPECT() *MockWebhookConfigRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockWebhookConfigRepository) GetByID(ctx context.Context, id int64) (*entities.WebhookConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.WebhookConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWebhookConfigRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWebhookConfigRepository)(nil).GetByID), ctx, id)
}
